### ISSUE TITLE
Some update good for SEO, keep it up!

### ISSUE THREAD

**Issue by superantim** [Slion/XenForoAddOnSlionsToc#4]
Your addon is good, keep it up
i have little idea for seo, can you update this for addon
i found here https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets
the heading h1 h2 h3 add more info (etc: id, data-text,.) same header title is good for seo like this
![114825769-d23f2e80-9df0-11eb-92f7-fe1cb5268329](https://user-images.githubusercontent.com/45330570/114825957-0ca8cb80-9df1-11eb-95d3-d2f3103b28bb.png)
![114825390-5ba23100-9df0-11eb-9157-35e0bba352f1](https://user-images.githubusercontent.com/45330570/114825962-0dd9f880-9df1-11eb-8088-0fb15e745aae.png)

**Comment by Slion** [comment]
Improving H elements with various attributes should be doable. 
Title element is outside the scope of that AddOn. Looks like XenForo is already supporting Title element as you would expect.

**Comment by Slion** [comment]
Looking into that again:
- `id` attribute is for anchor and now we do support named anchor.
- `data-text` is a custom attribute which is application specific I seriously doubt repeating the heading content in there helps search engine in anyway.
- `title` element is out of scope and already supported by XenForo

Thanks for your suggestions, glad you like that add-on, do check out the latest release.
